[project]
name = "virtual-stations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Flavien Lambert", email = "flavien.lambert@sencrop.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
virtual-stations = "virtual_stations:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
