---
name: Tests

on:
  workflow_call:

jobs:
  code_validation:
    runs-on: ubuntu-latest-arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync

      - name: Run tests
        run: uv run pytest
